// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
// Load .env.local first (Next.js convention), then .env so Prisma CLI sees DATABASE_URL
dotenv.config({ path: ".env.local" });
dotenv.config();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fallback so `prisma generate` (e.g. in postinstall on Vercel) runs without DATABASE_URL.
    // Real URL is used at runtime and for `prisma migrate deploy`.
    url: process.env.DATABASE_URL || "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
